### ISSUE TITLE
Add support for Wizard Form

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#36]
In redux-form there are some examples of types of forms, and one of them is the wizard form, I want to add support for this.

**Comment by andrerpena** [comment]
Yes that makes sense.

**Comment by danigomez** [comment]
@andrerpena we were thinking that also we can add the possibility to define a Conditional Wizard Form, it means that the user can also define which stepForm should be loaded using as condition the values loaded in the previous stepForm. 
That way is possible to load differents options in each step of the Wizard Form depending of the values selected in the previous step. 
What do you think??

**Comment by andrerpena** [comment]
That's a good thing. Some thoughts:
- Today, the "model" is the one single form, now, the model can be the "wizard", in the sense that, all fields from all steps are grouped together in a single "model" or "data context". If a field is repeated on step 3, for some reason, it will retain the value, because it's referencing the same field in the model. It's as if we're creating a "data context" that is maintained throughout the wizard. This is also interesting because if you go back, you have to restore the values.
- We can define multiple layouts to represent the steps.
- We can have a function to define the next "layout" based on the current "data context",  this way the workflow is not fixed.

**Comment by danigomez** [comment]
I agree!! :smile:

**Comment by danigomez** [comment]
Hi @andrerpena, we were thinking with Joni in a json structure like this:
```
{
  entities : {
    steps: {
          customer : {
              fields: {
                  name: {
                         type: "Input",
                          value: "Customer Name"
                   }
              }
              transition: (context) => { /* do stuff */}
           },
           billingInfo: {
              fields: {
                  billingAddress: {
                          type: "Input",
                            value: "Billing Address"
                   }
              }
              transition: (context) => { /* do stuff */}
           }, 
    }

  }
}
```

As the name says in `steps` you will define each step that the wizard form will have, there you define for each step a key which will be used as a name for the step, and all the fields that are used for that step, also you will define a transition function that will be receive the "wizart context" containing all the answers of all the questions in the wizard and there you can return the name of the step that you wanna go in certain condition, or leave it as default, which will transition to the first step that follows the one that you are in that moment.
We wait for your comments! :smile:

**Comment by JonatanSalas** [comment]
@danigomez you have implemented this already.. Should we close this issue?

**Comment by danigomez** [comment]
Yep, close It!

**Comment by JonatanSalas** [comment]
Good :smile:

**Comment by andrerpena** [comment]
I didn't see this yet but I'm looking forward to it. I just didn't have the time. Does it have a demo?

**Comment by JonatanSalas** [comment]
@andrerpena yes, it's published with the material ui demo! And it's in the bootstrap demo, but it's not updated in github pages u.u
