### ISSUE TITLE
Add the possibility to define callbacks for each event in Fields

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#40]
Hi @andrerpena, first for all thank you for including me in the organization! :smile: 
I was thinking to allow the developer to include in each field a callback for an event. For example,

``` javascript
{
   fields: {
         name: {
            type: "string",
            component: "Input",
             change : (event) => { console.log("Hey!, i'm changing! :P ";)}
         }
    }
}

```

And do this for each type of event, this way each field will be more cutomizable.
What do you think??

**Comment by andrerpena** [comment]
I like the idea and want to implement it, here are the things we should discuss before:

**Functions are automatically evaluated by RAF**
RAF evaluates every functions to literals before passing them to controls. This is how you can conditionally make a field visible. However, RAF ignores function metadata starting with $ or _ (I don't remember), so $onChange: () => {} will actually get to the component

**Redux-Form controlls the change and blur event of all fields**
That's how it triggers it's Redux actions that renders everything again. If we want to pass a custom handler, we have to wrap the original inside our own to make sure Redux-Form continues to work

**We have to think of use-cases first**
What would be the use cases? I can think of:
- Changing a field value as a result of another field changing. This is really interested so we can have calculated read-only fields. In order to do that, we have to trigger Redux-Form actions inside the change event to change the field value
- Dispatch an arbitrary redux action

Understanding real use cases is important so we can **know exactly what event args we will pass to the handler**.

**Funtions sucks**
One of the problems of RAF is that we deal with **invalid** JSON objects. I mean, JSON doesn't support functions. That means you can't store functions on Redis, or Mongo, or RethinkDB, or Firebase, or anywhere. And this is awful. I've being thinking about how to deal with that for weeks. I'm thinking of supporting text expressions that could be stored normally. We have to discuss it.

Never the less, this is a really good request and we should find a way to implement it.

**Comment by JonatanSalas** [comment]
MongoDB actually supports save functions

https://docs.mongodb.com/manual/tutorial/store-javascript-function-on-server/

About this issue, it's interesting to add support for this, since it could let the user easily match it's own event handlers. 

I will investigate a little bit and then we can advance on how to achieve it.

**Comment by JonatanSalas** [comment]
MongoDB actually supports save functions

https://docs.mongodb.com/manual/tutorial/store-javascript-function-on-server/

About this issue, it's interesting to add support for this, since it could let the user easily match it's own event handlers. 

I will investigate a little bit and then we can advance on how to achieve it.

**Comment by andrerpena** [comment]
Thanks. I didn't know about Mongo supporting functions.

Anyway.. RAF **does** support functions currently so I wouldn't remove it. I'd just think of a textual altenative that would be more JSON compliant and easy to store.

Back to the topic of this thread, I'm totally in.

**Comment by JonatanSalas** [comment]
@danigomez This issue is directly related to #18. As we have been talking, if we can integrate redux-form v6 successfully then, we can use the Field and FieldArray components in order to give them the event callbacks. 

Also, we have proposed this structure for the json field in the layouts: 

```javascript
{
  "name": "name",
  "displayName": "Name",	
  "component": "TextBox",
  "withRef": true || false,	
  //Callbacks to pass to Field/FieldArray components 
  "callbacks": {	
    "format": (value, name) => formattedValue,
    "validate": (value, allValues, props) => validatedValue,
    "normalize": (value, previousValue, allValues, previousAllValues) => nextValue,	
    "parse": (value, name) => parsedValue,
    "warn": (value, allValues, props) => warning
  },
  //Event callbacks to pass to the Field/FieldArray components
  "events": {
    "onChange": event => event,
    "onFocus": event => event,
    "onBlur": event => event,
    "onDragStart": event => event,
    "onDrop": event => event	
  },
  "styles": {
    "containerClassName": "container fluid",	
    "inputClassName": "input-group",
    "labelClassName": "form-control",
    "containerStyle": {
	//custom inline style
    },
    "inputStyle": {
       //custom inline style
    },
    "labelStyle": {
	//custom inline style
    }	
  }
}
```

**Comment by JonatanSalas** [comment]
With v1 repo this has first class support. We're not going to implement this for currently redux-autoform.
