### ISSUE TITLE
Are the Field and Layout schemas merged?

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#65]
Helloo @andrerpena, are you merging the layout and field data in this code??

```
     let groupField = layout.fields[i];
     let existingEntityProperty = entity.fields.find(field => field.name == groupField.name);

     let field = {...existingEntityProperty || {}, ...groupField};
```

If yes, why is the field and layout data in two different json?? is possible to configure the layout info in each field inside fields?? 

PS: I have an Squirtle xD

**Comment by andrerpena** [comment]
Haha.. I laughed at your Squirtle.

So, answering your question... Yes, I'm merging the **field from the layout** with the **field from the entity**.

Basically, this is how it works,  if you define a field in the entity and then define a field in a layout or layout group  with the **same name**, I merge all the metadata from these fields into one.

The reason why I do it so that you can **override** any metadata in a layout or layout group. For instance, let's say that a your contact's display name is simply "Name" in the entity. But then, in a particular layout, you want to call it "Contact name". All you have to do is to define a field called "name" in the layout (the same name as in the entity), and override the metadata there.

I didn't get the part `why is the field and layout data in two different json??`. They are not a different JSONs, they are in the same JSON, but the field can be defined in both the entity and multiple layouts and you can override information.

@JonatanSalas and me will have a Skype call this weekend where I'll help him understand the internals of metadata processing. If you want you can participate.

Does that answer your question?

**Comment by danigomez** [comment]
Got it! :smile:
