### ISSUE TITLE
Issue with Fields

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#84]
I'm working with Material UI extension and I have the following trouble. In order to be able to show the errors string in a Component I evaluate the values touched and active received from redux-autoform. 

Those values don't update when I'm performing a touch on the TextBox and I start to make my input. I have logged the node_modules redux-autoform version that I have, that It's the latest in experimental tag. 

This is what you can see, when I keep on typing the value in the fields object updates properly, but that's not the case for the other values that stay always in false. 

I started to think that this could be an error that I have introduced yesterday when performing the update to pass an error object to the ButtonToolbar, but after checking the code in AutoformInternal it seems to be well and don't alter the fields object.

I will try to check if I can reproduce the bug in bootstrap-ui project!

![captura de pantalla de 2016-09-08 13-29-24](https://cloud.githubusercontent.com/assets/7697196/18357698/53332ee8-75c8-11e6-87d8-05d10aebf957.png)

**Comment by JonatanSalas** [comment]
With Bootstrap works only the touched property, so I suppose this could be related to react-tap-event-plugin and redux-form not triggering an touched event. I have to look this better.

**Comment by andrerpena** [comment]
@JonatanSalas , I may be wrong, but I think `touched` will be set to `true` on 2 situations:
- When you change the field
- When you "blur" the field (click on it and then leave)

In order for the second to work, you have to pass the Redux-Form `onBlur` handler to the input. I think you're not doing this because I tested on your demo. If you click and leave a field it's not being marked as touched as it happens with the BS UI.

**Comment by JonatanSalas** [comment]
oooooooooooooooooooooooooooooh I'm a fooooool :( thank you!

**Comment by JonatanSalas** [comment]
Solved! Thank you very much!

**Comment by andrerpena** [comment]
:smile:
